# Generated by Django 5.0.6 on 2024-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.TextField(blank=True, help_text='max 30 words', null=True),
        ),
    ]
