# Generated by Django 5.0.6 on 2024-11-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-created']},
        ),
    ]
